- src/components/Header.astro
- src/components/Hero.astro
- src/components/TableOfContentList.tsx
- Prefixed links using base value, which is configured in astro.config.mjs as GitHub Pages need the name of the repo as the base value
_ex:  If base is "docs-next"_
_Old link: https://superofficedocs.com/release-notes/_
_New link: https://superofficedocs.com/docs-next/release-notes/_
> fix: added base to prefix links on Hero section and TableOfContent

- src/components/TableOfContentList.tsx
- src/content/docs/en/learn/toc.yml
- src/layouts/Markdown.astro
- src/pages/de/[...slug].astro
- src/pages/en/[...slug].astro
- fixed routing of table of content
- optimized en and de [..slug] files
> fix: table of content routing

- .github/workflows/deploy.yml
- astro.config.mjs
- removed trailing slash to fix the relative path linking issue when deplying to github pages
> fix: removed trailing slash in astro.config.mjs

- src/components/PageHeader.astro
- src/layouts/CategoryLandingLayout.astro
- src/layouts/Markdown.astro
- src/pages/de/[category].astro
- src/pages/en/[...slug].astro
- src/pages/en/[category].astro
- fixed navigation issue in pageHeader edit button to the relevant page in github repo
**This PR fixes issue #90**
> fix page header edit button navigation issue

- src/components/Footer.astro
- src/components/OnThisArticle.tsx
- src/components/TableOfContentList.tsx
- src/layouts/Base.astro
- src/layouts/Markdown.astro
Changes related to the Table of Contents and Routing
- Integrated the Astro client router to selectively refresh components when routing to a new page
- Changed the transition of TableOfContent to persist when routing to a new page
Changes related to the Footer
- Changed footer to appear when user scrolls to the bottom of the page
- Changed styling of footer to match SuperOffice color theme
This PR introduces fixes to Bug #92
> fix: table of Content refresh issue and footer style changes

- src/components/TableOfContentList.tsx
- src/layouts/Markdown.astro
- Changed TableOfContent height to fit to content
- Changed TableOfContent responsive width
- Optimized Markdown Layout to be responsive
> style: TableOfContent and Markdown Layout style changes

- src/components/Hamburger.astro
- src/components/Header.astro
- src/components/PageHeader.astro
- fixed responsive issues in mobile view
- changed styling in mobile view
> style: fixed header mobile responsiveness

- src/components/Footer.tsx
- src/layouts/Base.astro
- Changed footer mobile view styling and responsiveness
- Changed height and arrangement of footer links in desktop view
> style: fixed styling issues in footer mobile & desktop view

- src/components/Footer.tsx
- src/components/TableOfContentList.tsx
- src/layouts/Base.astro
- reduced top margin in the main table of the TOC
- changed the alignment of text to left
- changed the width of sub-tables in TOC
- adjusted a few other minor style changes
> style: table of content styling

- astro.config.mjs
- src/components/Header.astro
- src/components/Search.astro
- src/components/WebApiClass.astro
- src/layouts/Base.astro
- src/layouts/CategoryLandingLayout.astro
- src/layouts/Markdown.astro
- src/layouts/SubCategoryLandingLayout.astro
- src/navigation.js
- src/pages/404.astro
- src/pages/de/[...slug].astro
- src/pages/de/[category].astro
- src/pages/en/[...slug].astro
- src/pages/en/[category].astro
- src/pages/en/[subcategory].astro
- src/pages/en/api/reference/webapi/[...slug].astro
- src/pages/index.astro
- src/pages/release-notes/[...slug].astro
- src/styles/main.css
- src/styles/pagefind/ui.css
- src/types/pagefind-default-ui.d.ts
<ul> <li>Added search functionality using Astro's Pagefind integration. </li>
<ul>
<li> Created a custom Search.astro component by customizing pagefind's default component in order to change the bundle path URL. </li>
<li> Created a custom style sheet (styles/pagefind/ui.css) for the search component by customizing pagefind's default stylesheet. </li>
<li> Added a language prop to multiple components to support language translation in search </li>
</ul>
</ul>
- Changed header elements to h2 header tags in webApiClass.astro
> feat: search

- src/components/GradientBanner.astro
- src/components/Hero.astro
- src/pages/404.astro
- Added variable height to the  GradientBanner component using props to match different height requirements for the index page and 404 page
> fix: added variable height to gradientBanner component

- src/components/WebApiItem.astro
- Changed description in WebApiItem.astro to render HTML
**This PR fixes #144**
> fix: Raw HTML bleeds through in WebApi

- src/pages/contribute/[...slug].astro
- src/pages/de/[...slug].astro
- src/pages/en/[...slug].astro
- src/pages/en/api/reference/webapi/[...slug].astro
- src/pages/release-notes/[...slug].astro
- src/utils/slugUtils.ts
- renamed util stripMarkdownSlug to stripFilePathAndExtension
- updated stripFilePathAndExtension to remove .yaml and yml in addition to .md extensions
> fix: updated and renamed stripFilePathAndExtension

- src/content/docs/en/api/reference/netserver/core/toc.yml
- src/content/docs/en/api/reference/netserver/services/toc.yml
- src/content/docs/en/api/reference/netserver/toc.yml
- src/content/docs/en/api/reference/restful/agent/toc.yml
- src/content/docs/en/api/reference/restful/rest/toc.yml
- src/content/docs/en/api/reference/restful/toc.yml
- src/content/docs/en/api/reference/web/toc.yml
- added toc files from api/reference folder into  src/content
> chore: added toc fies from api/reference

- package-lock.json
- package.json
- added cross-env package to set up env to support all platforms (Windows, Linux, MacOS)
Package Changes
- Added cross-env: ^7.0.3
> feat: added cross-env package to set env

- src/content.config.ts
- updated content.config.ts to render contribution files in both build (API_ONLY= true and API_ONLY=false)
- fixes build issues introduced by PR #162
> fix: updated contribution collection import pattern

- astro.config.mjs
Testing this on the full build
> #184 Conditionally exclude static landing page in config

- src/components/Header.astro
- src/navigation.js
- src/styles/main.css
- changed highlighting color of the search results in landing page search bar to match the design spec
- fixed responsiveness of the header in various breakpoints
- simplified and cleaned up code in header component
> style: changed styling in search bar and fixed header responsiveness

- src/content.config.ts
- src/pages/da/[...slug].astro
- src/pages/da/[...subcategory].astro
- src/pages/da/[category].astro
- src/pages/nl/[...slug].astro
- src/pages/nl/[...subcategory].astro
- src/pages/nl/[category].astro
- src/pages/no/[...slug].astro
- src/pages/no/[...subcategory].astro
- src/pages/no/[category].astro
- src/pages/sv/[...slug].astro
- src/pages/sv/[...subcategory].astro
- src/pages/sv/[category].astro
NO, DA, SV, and NL added using same pattern as DE
* Added headings to make the file more scannable as it grows
* Removed trivial comments
> #182 add all languages

- src/content.config.ts
... to include webhook reference and any other md file in automation except netserver-scripting/reference
> #212 Loosen exclude pattern for automation

- src/components/Link.astro
- src/components/YamlCodeBlock.astro
- src/components/YamlExampleBlock.astro
- src/components/YamlManagedReferenceClass.astro
- src/components/YamlManagedReferenceConstructor.astro
- src/components/YamlManagedReferenceContent.astro
- src/components/YamlManagedReferenceEnum.astro
- src/components/YamlManagedReferenceMethod.astro
- src/components/YamlManagedReferenceNamespace.astro
- src/content.config.ts
- src/content.schema.ts
- src/layouts/YamlManagedReference.astro
- src/pages/en/automation/crmscript/[...slug].astro
- src/types/YamlManagedReferenceTypes.ts
- src/utils/yamlManagedReferenceUtils.ts
Designed to be extendable to handle netserver core/services and webapi too.
Layout component does not handle tocData and headings (unrelated to processing YamlManagedReference).
> #215 Initial YamlManagedReference handling for CRMScript

- src/components/Header.astro
- changed a few responsiveness styling in the header
> style: minor header styling changes

- src/content.config.ts
- src/plugins/AddIncludesToMarkdown.js
- A Temporary content.config.ts file had been accidentally included with a commit in PR #249. This PR reverts that file
> fix: revert accidential commit of content.config file

- src/components/PageHeader.astro
- src/layouts/SubCategoryLandingLayout.astro
- src/pages/da/[...subcategory].astro
- src/pages/de/[...subcategory].astro
- src/pages/en/[...subcategory].astro
- src/pages/nl/[...subcategory].astro
- src/pages/no/[...subcategory].astro
- src/pages/sv/[...subcategory].astro
- src/utils/tocUtils.ts
- Updated TOC baseSlug in subcategory layout and [...subcategory].astro pages for en, da, de, nl, no, sv
- Updated responsive styling in TOC of subcategory pages
- Fixes missing TOC in pages like /en/onsite/install
> fix: subcategory toc

- src/components/WebApiClass.astro
- src/components/WebApiItem.astro
- src/components/WebApiPage.astro
- src/types/WebAPITypes.ts
- Added Inherited Members property to WebAPI
> feat: webapi inherited members

- src/utils/slugUtils.ts
> fix: removed manual netserver url mapping in api

- astro.config.mjs
- Setup da, nl, no, sv languages to fallback to en
> feat: setup fallback languages
